version: "3.9"

services:
  app:
    image: learntogether-api:latest
    container_name: learntogether-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy  # Add health check dependency
    environment:
      SPRING_APPLICATION_NAME: learntogether
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/learntogether
      SPRING_DATASOURCE_USERNAME: soufiane
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_LIQUIBASE_ENABLED: 'true'
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.yaml
    ports:
      - "8080:8080"
    networks:
      - learntogether-network
    restart: unless-stopped  # Add restart policy

  postgres:
    image: postgres:15-alpine  # Use Alpine for smaller image size
    container_name: learntogether-postgres
    environment:
      POSTGRES_DB: learntogether
      POSTGRES_USER: soufiane
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - learntogether-network
    healthcheck:  # Add healthcheck for postgres
      test: ["CMD-SHELL", "pg_isready -U soufiane -d learntogether"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  learntogether-network:
    driver: bridge

volumes:
  postgres-data: