spring:
  application:
    name: LearnTogether
  datasource:
    url: jdbc:postgresql://localhost:5432/learn_together
    username: postgres
    password: ""
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jdbc:
    template:
      query-timeout: 5

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG